#!/usr/bin/env bash
# Transfers a file from our client to a server

sudo apt-get update -y
sudo apt-get install nginx -y 
sudo ufw allow 'Nginx HTTP'
sh -c 'echo "Holberton School" > /var/www/html/index.html'
sudo systemctl start nginx.service