#!/usr/bin/env bash
# ahhhhhhh

sudo touch /var/www/html/error_404.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error_404.html
sudo sed -i '25i\	error_page 404 /error_404.html;' /etc/nginx/sites-available/default
sudo service nginx restart